# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#Sitemap
gems:
  - jekyll-sitemap
  
# Site settings
title: DeanOfGreen
email: armandforprecinct420@gmail.com
description: "Armand Davis, or the Dean of Green, as he is known among his close friends, family, and supporters, is running for the post of Democratic Precinct Committeeperson for Oregon Precinct 420. Through his progressive and modern views on trade and the economy, the Dean of Green will blaze a trail bringing a whole new high to Precinct 420. Vote by May 17!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://deanofgreen420.win" # the base hostname & protocol for your site
instagram_username: dean_of_green420

# Build settings
markdown: kramdown

#defaults
defaults:
  - 
    scope: 
      path: ""
    values:
      author: "Dean of Green"